git:
  depth: false
language: node_js
node_js:
- '10'
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
  - "~/.cache"
  - "~/.npm"
install:
- npm ci
before_script:
- npm start -- --silent &
script:
- npm run lint || travis_terminate 1
- "$(npm bin)/cypress run --record || travis_terminate 1"
- npm run build || travis_terminate 1
deploy:
  provider: s3
  access_key_id: AKIAXUVNCH2WIPGM7ONW
  secret_access_key:
    secure: M7+4WK9iJ7Nzorr6L0W6uE2PaWE/gsTdmMi9kNsOzxRWy3To9azjfZSNaBkV4hWE0EEryO5YaQoQyb/znnN3zw/Onm0DshSeMhKCkjQKwwBKSJAq8G3NTh49khBOaMJJ9ZnEEaYLl2u2/1NlRaNuqPxu9UgH1SyJkRyR8s0DgjcIFM3/x95qqmFix3OGePNgxO/Xi6H4Kq3yYOdVxctoEkROLg5+K4S+W5ofi2V9EEC+ajstKtKv3wJ9mCI4UjiWQH8XvTNOFx+RXzEB5pqNPOyfbe2qDGZfhFihSJ2Gi28KjZxN0SQxXp2306/meBl9QX7ec1xcOfYYxTE2TkLm9PAio/HxCnNPDIU3V12TLHCq5KOe2BOeVRFKatoKC/VxHjdrBi+F1GWIq6sj9rKbp29NK7Rk9VM9o9mGpEQ1wO2R9QyeKbfVjatxiYVbawJtiYd//VYAmxxdVAQYIapAQOsPCU1JZRGlvKvmjIa1YStD726bwWzK4zP9hleK3XV1rzSYJLEi1PEuHaBimU9f43jfsjn7/0HAau7lTlb1TzECiEQHRnVUaAbR8vvGPwhLoyiPXAN0U0oB+hVAM349ENqCf2K85XwGjbJmqQu9k0R1pLy0AhQ96H9Re82hcleAyh7AecMxB0ClbI0yWo1+OcjhZ7Cxn6CXNdR1SKms1Bc=
  bucket: klukka.irdn.is
  region: eu-west-1
  local_dir: build
  detect_encoding: true
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    secure: F51jvJojwjKl/mvlHcZkQrhPhNes8jNTNkXGi9Rp3UNq9YZ8AoI0z221QPRAsin11SZXyTbgm+vGNS+T2RGeDZWw4muKynRNCvk6mr6XPV59ySYjyVfs7oNTMua6n4dNwbOJrCmv8SgDJT5DxzkavtM+XFAMad965r6/Sm8espBWZAdGG1YC3Huc86xYgl4GO3/cgEwGWGvpS8C7Tbn48b91Cs57Hf2dxoGGCtftbssBKa0NYTjtRp1zsTexrklBzRe0XNhncV09i3lpNy+38bdFWlYY+XIi+G2TIJVYwGmwj2owlLM/3xeg0IqPPJ1QROYFDhQkyzjw31/OjiQcqYbz4DjosJ/YNI8vHNEzgTCpp8ekXlZf3s+QL6UOUpD9rBukGUP4zITPasfMpFguisvxtZKHFRs1SFG4q5pSDFwsbnIuF/uxwQgsCUPDWCwMvJ0pDi2IZLJtlo8ZhYbvQMzfNg1HvBvkw4lFhhWnIsZug+OHqPAnxP8naWw1L/38hgXXg+KzaV9H76XuXNLuOaMVy9qN/fbWb5WYcJL/kWXqXYMjvhE6wXg0WKtMai+J9jikphji54cc+ro8e2hcRfsWxGaR9z4AgBW1ir8VxoZDiAhFoQ22msdI2moBP8mUGPSv8UJQeDUMrfq7zYSVn2Ta4/vKfih7LoNdsFoL4SY=
  on_start: always
env:
  global:
    secure: mgdw5W6h9e5unmYBaB5OlnQOFqSeIUyMLGppK11FYQSw7Rpeoa/gNxaVbGVYXDAzXK42m6qFr9gSEirDw6w6YYU9veEzLfXeidJsNoIVYFw9q3e0AVR8nPscuJE0I+D2grta39lL/YTOf7l+VF2H5dTJX8ZY/B+q6qSp1RsBYcDodxqkwEUjjMOcfOqxnCpjvlS7HETogWpgxhT1ZKxO89tKKIZKUUGJcyKPEErLn/8MmOd6oajsqZhz9ck+SB7h4aZQM+KucEHlvl7tfwPk8GhTCKD6zdU7WRAipdb2cGN+EbuEmnWXEBq7j+hrKFUqV6RIcW50KxOxNlp/KCtWhZjRRQtZYzXCRHcKQYphlH6LRVA4R45ZvWbzyeJVKwJ0f/tEJmznc8LfW6FElhPe/Nf97s0u0Umu2S5HkguS/PV2eRWjMJipLv4ykccT8cYO86bO8NjC7wmSPcaM5MbDGODfC2Flag+CMRtqBpg9X+I5Ys5AKidxnIK7H5c+D54ViKB0rQ1WTQ2SNBtMofrV9XxwVNr5RdxPm9SSnfcttP7eycYFSjU7tGmmIP/YGKD4anHCD+z+wsPrybBUcvHW0BFncsEjbXi7Fsp72RsBcRBuU/wNPrZeIMTEFtB89aE1mqy3G2B3ZlYyM59y1KORMBmb/96cS4gCZ1EuVR6TW4g=
