git:
  depth: false
language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm run lint
- npm run test
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAXUVNCH2WIPGM7ONW
  secret_access_key:
    secure: M7+4WK9iJ7Nzorr6L0W6uE2PaWE/gsTdmMi9kNsOzxRWy3To9azjfZSNaBkV4hWE0EEryO5YaQoQyb/znnN3zw/Onm0DshSeMhKCkjQKwwBKSJAq8G3NTh49khBOaMJJ9ZnEEaYLl2u2/1NlRaNuqPxu9UgH1SyJkRyR8s0DgjcIFM3/x95qqmFix3OGePNgxO/Xi6H4Kq3yYOdVxctoEkROLg5+K4S+W5ofi2V9EEC+ajstKtKv3wJ9mCI4UjiWQH8XvTNOFx+RXzEB5pqNPOyfbe2qDGZfhFihSJ2Gi28KjZxN0SQxXp2306/meBl9QX7ec1xcOfYYxTE2TkLm9PAio/HxCnNPDIU3V12TLHCq5KOe2BOeVRFKatoKC/VxHjdrBi+F1GWIq6sj9rKbp29NK7Rk9VM9o9mGpEQ1wO2R9QyeKbfVjatxiYVbawJtiYd//VYAmxxdVAQYIapAQOsPCU1JZRGlvKvmjIa1YStD726bwWzK4zP9hleK3XV1rzSYJLEi1PEuHaBimU9f43jfsjn7/0HAau7lTlb1TzECiEQHRnVUaAbR8vvGPwhLoyiPXAN0U0oB+hVAM349ENqCf2K85XwGjbJmqQu9k0R1pLy0AhQ96H9Re82hcleAyh7AecMxB0ClbI0yWo1+OcjhZ7Cxn6CXNdR1SKms1Bc=
  bucket: klukka.irdn.is
  region: eu-west-1
  local_dir: build
  detect_encoding: true
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    rooms:
      - secure: F51jvJojwjKl/mvlHcZkQrhPhNes8jNTNkXGi9Rp3UNq9YZ8AoI0z221QPRAsin11SZXyTbgm+vGNS+T2RGeDZWw4muKynRNCvk6mr6XPV59ySYjyVfs7oNTMua6n4dNwbOJrCmv8SgDJT5DxzkavtM+XFAMad965r6/Sm8espBWZAdGG1YC3Huc86xYgl4GO3/cgEwGWGvpS8C7Tbn48b91Cs57Hf2dxoGGCtftbssBKa0NYTjtRp1zsTexrklBzRe0XNhncV09i3lpNy+38bdFWlYY+XIi+G2TIJVYwGmwj2owlLM/3xeg0IqPPJ1QROYFDhQkyzjw31/OjiQcqYbz4DjosJ/YNI8vHNEzgTCpp8ekXlZf3s+QL6UOUpD9rBukGUP4zITPasfMpFguisvxtZKHFRs1SFG4q5pSDFwsbnIuF/uxwQgsCUPDWCwMvJ0pDi2IZLJtlo8ZhYbvQMzfNg1HvBvkw4lFhhWnIsZug+OHqPAnxP8naWw1L/38hgXXg+KzaV9H76XuXNLuOaMVy9qN/fbWb5WYcJL/kWXqXYMjvhE6wXg0WKtMai+J9jikphji54cc+ro8e2hcRfsWxGaR9z4AgBW1ir8VxoZDiAhFoQ22msdI2moBP8mUGPSv8UJQeDUMrfq7zYSVn2Ta4/vKfih7LoNdsFoL4SY=
    on_start: always